[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
portfolio_management = "E31tdKPpY99KpeWX1TKzi5wycWApYTJ7UAaiKNgUrhBF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/portfolio_management"]

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
