name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: List rustup toolchains
      run: rustup toolchain list
    - name: Set default toolchain
      run: rustup default stable
    - name: List rustup toolchains
      run: rustup toolchain list
    - name: Generate new keygen
      run: solana-keygen new
    - name: Set solana target cluster to local
      run: solana config set --url http:localhost:8899
    - name: Check solana config
      run: solana config get
    - name: Install yarn dependencies
      run: yarn install
    - name: Build
      run: anchor build
    - name: Run tests
      run: anchor test
